import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import MarketingNav from '@/components/MarketingNav';
import Footer from '@/components/marketing/Footer';
import { ShieldAlert, FileText, CheckCircle2, ArrowLeft, Scale, AlertTriangle, ArrowRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | CashFloor',
  description: 'Terms of service, educational disclaimers, and software license for the CashFloor runway calculation platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--cf-bg)] text-[var(--cf-text)] transition-colors duration-300 font-sans flex flex-col">
      <MarketingNav />
      
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 md:px-8 pt-6 pb-20 w-full space-y-10">
        {/* Navigation Breadcrumb */}
        <div className="flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-mono font-medium text-[var(--cf-text-muted)] hover:text-[var(--cf-accent)] transition-colors group"
          >
            <ArrowLeft className="w-3.5 h-3.5 group-hover:-translate-x-1 transition-transform" />
            <span>Back to Home</span>
          </Link>

          <span className="px-3 py-1 rounded-full text-[11px] font-mono font-semibold bg-[var(--cf-surface-alt)] text-[var(--cf-text-muted)] border border-[var(--cf-border)]">
            Legal Terms &amp; Conditions
          </span>
        </div>

        {/* Header */}
        <div className="space-y-4">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-serif font-bold tracking-tight text-[var(--cf-text)]">
            Terms of Service
          </h1>
          <p className="text-sm sm:text-base text-[var(--cf-text-muted)] leading-relaxed">
            Last Updated: September 2026 · Effective for all users worldwide
          </p>
        </div>

        {/* Safe-Harbor Educational Notice Banner */}
        <div className="p-6 rounded-2xl border border-amber-500/30 bg-amber-500/10 space-y-3">
          <div className="flex items-center gap-2 text-amber-800 dark:text-amber-300 font-serif font-bold text-base">
            <AlertTriangle className="w-5 h-5 text-amber-600" />
            <span>Mandatory Safe-Harbor Educational Disclaimer</span>
          </div>
          <p className="text-xs sm:text-sm text-amber-900/80 dark:text-amber-200/80 leading-relaxed font-sans">
            CashFloor is a mathematical simulation, scenario modeling, and cash flow visualization software application. <strong>CashFloor does not provide formal investment advice, tax filings, legal counsel, or certified public accounting services.</strong> The calculations, 20th percentile income floors, tax withholding estimates, and runway exhaustion horizons generated by the software are hypothetical estimates for educational and business planning purposes only. Always consult a Certified Public Accountant (CPA) or qualified attorney for official tax filings and legal compliance.
          </p>
        </div>

        {/* Terms Articles */}
        <div className="space-y-8 text-xs sm:text-sm leading-relaxed text-[var(--cf-text-muted)]">
          <section className="p-6 rounded-2xl border border-[var(--cf-border)] bg-[var(--cf-surface)] space-y-3">
            <h2 className="text-base font-serif font-bold text-[var(--cf-text)] flex items-center gap-2">
              <Scale className="w-4 h-4 text-[var(--cf-accent)]" />
              <span>1. Agreement to Terms</span>
            </h2>
            <p>
              By accessing, browsing, or utilizing CashFloor (accessible via cashfloor.app or affiliated domains), you agree to be bound by these Terms of Service, all applicable laws and regulations, and our Privacy Policy. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-[var(--cf-border)] bg-[var(--cf-surface)] space-y-3">
            <h2 className="text-base font-serif font-bold text-[var(--cf-text)] flex items-center gap-2">
              <FileText className="w-4 h-4 text-[var(--cf-accent)]" />
              <span>2. Software License &amp; Usage Rights</span>
            </h2>
            <p>
              CashFloor grants you a personal, non-exclusive, non-transferable, revocable license to utilize our client-side software algorithms, calculation tools, and exports solely for your personal freelancing or internal business management operations.
            </p>
            <p>
              You agree not to decompile, reverse-engineer, replicate, scrap, or redistribute the proprietary quantitative modeling engines without prior written authorization from CashFloor.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-[var(--cf-border)] bg-[var(--cf-surface)] space-y-3">
            <h2 className="text-base font-serif font-bold text-[var(--cf-text)] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[var(--cf-accent)]" />
              <span>3. User Accounts and Data Integrity</span>
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your authentication tokens and magic links. CashFloor calculates outputs based strictly on data provided by you or imported via your CSV files. We make no representations or warranties regarding the mathematical accuracy of inputs provided by external banking institutions.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-[var(--cf-border)] bg-[var(--cf-surface)] space-y-3">
            <h2 className="text-base font-serif font-bold text-[var(--cf-text)] flex items-center gap-2">
              <ShieldAlert className="w-4 h-4 text-[var(--cf-accent)]" />
              <span>4. Limitation of Liability</span>
            </h2>
            <p>
              In no event shall CashFloor, its developers, affiliates, or licensors be liable for any indirect, incidental, punitive, or consequential damages (including, without limitation, loss of business revenue, missed tax deadlines, penalties assessed by tax authorities, or liquidity shortfalls) arising out of the use or inability to use the software.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
