'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ShieldCheck,
  User,
  Mail,
  Briefcase,
  Lock,
  LogOut,
  ArrowLeft,
  Sparkles,
  Database,
  CheckCircle2,
  Key,
  ShieldAlert,
  Smartphone,
  Download,
  Trash2,
  ExternalLink,
  RefreshCw,
  Clock,
  Layers,
  Check,
  Sliders
} from 'lucide-react';
import DashboardNav from '@/components/DashboardNav';
import { useAuth, DEMO_PERSONAS, DemoPersonaKey } from '@/lib/auth/AuthContext';

export default function AccountPage() {
  const { user, isAuthenticated, isPro, signOut, openAuthModal, signInWithDemo } = useAuth();
  const [activeTab, setActiveTab] = useState<'profile' | 'security' | 'billing' | 'data'>('profile');
  const [purgeSuccess, setPurgeSuccess] = useState(false);
  const [exportSuccess, setExportSuccess] = useState(false);

  const displayName = user?.name || user?.email?.split('@')[0] || 'Independent Pro';

  const handleExportAllData = () => {
    try {
      const exportPayload = {
        exportDate: new Date().toISOString(),
        user: {
          id: user?.id,
          email: user?.email,
          name: user?.name,
          role: user?.role,
          tier: isPro ? 'Pro' : 'Starter',
        },
        storageType: 'Client-Encrypted Local Vault',
        disclaimer: 'Generated by CashFloor — Not financial or tax advice.',
      };
      const blob = new Blob([JSON.stringify(exportPayload, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `cashfloor-data-export-${new Date().toISOString().slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);
      setExportSuccess(true);
      setTimeout(() => setExportSuccess(false), 3000);
    } catch {
      // ignore
    }
  };

  const handlePurgeLocalData = () => {
    if (confirm('Are you sure you want to clear your local ledger cache on this device? Your account will remain active.')) {
      try {
        localStorage.removeItem('cashfloor_records');
        localStorage.removeItem('cashfloor_assumptions');
        setPurgeSuccess(true);
        setTimeout(() => setPurgeSuccess(false), 3000);
      } catch {
        // ignore
      }
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-[var(--cf-bg)] text-[var(--cf-text)] transition-colors duration-300">
      <DashboardNav />

      <main className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-6 md:px-8 py-10 space-y-8">
        
        {/* Navigation Breadcrumbs */}
        <div className="flex items-center justify-between">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--cf-text-muted)] hover:text-[var(--cf-text)] transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Dashboard</span>
          </Link>

          <span className="text-xs font-mono text-[var(--cf-text-faint)]">
            Account &amp; Security Command Center
          </span>
        </div>

        {/* ── Top User Profile Banner ── */}
        <div 
          className="p-6 sm:p-8 rounded-3xl border relative overflow-hidden shadow-xl"
          style={{
            background: 'var(--cf-surface)',
            borderColor: 'var(--cf-border)',
            boxShadow: 'var(--cf-shadow-md)',
          }}
        >
          <div
            className="absolute top-0 right-0 w-96 h-96 rounded-full blur-3xl pointer-events-none opacity-10"
            style={{ background: 'var(--cf-accent)' }}
          />

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 relative z-10">
            <div className="flex items-center gap-4 sm:gap-6">
              {/* Initials badge */}
              <div
                className="w-16 h-16 sm:w-20 sm:h-20 rounded-2xl flex items-center justify-center text-2xl font-serif font-bold text-white shadow-lg shrink-0"
                style={{ background: 'linear-gradient(135deg, #2F6F62 0%, #0f564a 100%)' }}
              >
                {displayName.slice(0, 2).toUpperCase()}
              </div>

              <div>
                <div className="flex flex-wrap items-center gap-2 mb-1">
                  <h1 className="font-serif text-2xl sm:text-3xl font-semibold tracking-tight text-[var(--cf-text)]">
                    {displayName}
                  </h1>
                  <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold uppercase tracking-wider text-emerald-600 bg-emerald-500/10 border border-emerald-500/20">
                    <Sparkles className="w-3 h-3" />
                    {isPro ? 'Pro Floor Active' : 'Starter Tier'}
                  </span>
                </div>

                <p className="text-xs text-[var(--cf-text-muted)] flex items-center gap-2">
                  <span>{user?.email || 'Guest Explorer Session'}</span>
                  <span>·</span>
                  <span className="font-mono text-[var(--cf-accent)]">
                    {user?.role || 'Independent Consultant'}
                  </span>
                </p>

                <div className="flex items-center gap-2 mt-2 text-[11px] font-mono text-[var(--cf-text-faint)]">
                  <span className="w-2 h-2 rounded-full bg-emerald-500" />
                  <span>Private Local Vault: Active &amp; Encrypted</span>
                </div>
              </div>
            </div>

            {/* Quick Actions */}
            <div className="flex items-center gap-2.5">
              {isAuthenticated ? (
                <button
                  type="button"
                  onClick={signOut}
                  className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold border transition-all cursor-pointer"
                  style={{
                    borderColor: 'var(--cf-border)',
                    color: 'var(--cf-caution)',
                    background: 'var(--cf-caution-bg)',
                  }}
                >
                  <LogOut className="w-4 h-4" />
                  <span>Sign Out</span>
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => openAuthModal()}
                  className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-xs font-semibold text-white transition-all cursor-pointer shadow-md"
                  style={{ background: 'linear-gradient(135deg, #2F6F62, #1a4f45)' }}
                >
                  <User className="w-4 h-4" />
                  <span>Sign In</span>
                </button>
              )}
            </div>
          </div>

          {/* ── Sub-Navigation Tabs ── */}
          <div className="flex items-center gap-2 mt-8 pt-6 border-t border-[var(--cf-border-soft)] overflow-x-auto">
            {[
              { id: 'profile', label: 'Identity & Personas', icon: User },
              { id: 'security', label: 'Security & Sessions', icon: Lock },
              { id: 'billing', label: 'Subscription & Billing', icon: Sparkles },
              { id: 'data', label: 'Data Sovereignty & Vault', icon: Database },
            ].map(tab => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  type="button"
                  onClick={() => setActiveTab(tab.id as any)}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-mono transition-all cursor-pointer whitespace-nowrap border"
                  style={{
                    background: isActive ? 'var(--cf-surface-alt)' : 'transparent',
                    borderColor: isActive ? 'var(--cf-accent)' : 'transparent',
                    color: isActive ? 'var(--cf-text)' : 'var(--cf-text-muted)',
                    fontWeight: isActive ? 600 : 400,
                  }}
                >
                  <Icon className="w-3.5 h-3.5" style={{ color: isActive ? 'var(--cf-accent)' : 'inherit' }} />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* ── Tab Content ── */}
        <AnimatePresence mode="wait">
          
          {/* TAB 1: IDENTITY & PERSONAS */}
          {activeTab === 'profile' && (
            <motion.div
              key="profile"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="space-y-6"
            >
              {/* Demo Persona Switcher */}
              <div 
                className="p-6 sm:p-8 rounded-3xl border space-y-4"
                style={{ background: 'var(--cf-surface)', borderColor: 'var(--cf-border)' }}
              >
                <div className="flex items-center justify-between pb-3 border-b border-[var(--cf-border-soft)]">
                  <div>
                    <h2 className="text-base font-serif font-bold text-[var(--cf-text)]">
                      1-Click Freelance Persona Profiles
                    </h2>
                    <p className="text-xs text-[var(--cf-text-muted)] mt-0.5">
                      Instantly test different freelance financial realities without typing test data
                    </p>
                  </div>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[var(--cf-surface-alt)] text-[var(--cf-text-faint)]">
                    Instant Demo Switch
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
                  {(Object.keys(DEMO_PERSONAS) as DemoPersonaKey[]).map(key => {
                    const p = DEMO_PERSONAS[key];
                    const isSelected = user?.email === p.email;

                    return (
                      <div
                        key={key}
                        onClick={() => signInWithDemo(key)}
                        className="p-4 rounded-2xl border transition-all cursor-pointer flex flex-col justify-between"
                        style={{
                          background: isSelected ? 'var(--cf-surface-alt)' : 'var(--cf-surface)',
                          borderColor: isSelected ? 'var(--cf-accent)' : 'var(--cf-border)',
                          boxShadow: isSelected ? '0 4px 16px rgba(47,111,98,0.12)' : 'none',
                        }}
                      >
                        <div>
                          <div className="flex items-center justify-between mb-2">
                            <span className="font-semibold text-xs text-[var(--cf-text)]">
                              {p.name}
                            </span>
                            {isSelected && (
                              <span className="w-2 h-2 rounded-full bg-emerald-500" />
                            )}
                          </div>
                          <p className="text-[11px] font-mono text-[var(--cf-accent)] mb-1">
                            {p.role}
                          </p>
                          <p className="text-[11px] text-[var(--cf-text-muted)] leading-relaxed">
                            {p.description}
                          </p>
                        </div>

                        <div className="mt-4 pt-3 border-t border-[var(--cf-border-soft)] flex items-center justify-between text-[11px] font-mono">
                          <span className="text-[var(--cf-text-faint)]">Monthly Income</span>
                          <span className="font-bold text-[var(--cf-text)]">${p.monthlyIncome.toLocaleString()}</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </motion.div>
          )}

          {/* TAB 2: SECURITY & SESSIONS */}
          {activeTab === 'security' && (
            <motion.div
              key="security"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="space-y-6"
            >
              <div 
                className="p-6 sm:p-8 rounded-3xl border space-y-6"
                style={{ background: 'var(--cf-surface)', borderColor: 'var(--cf-border)' }}
              >
                <div>
                  <h2 className="text-base font-serif font-bold text-[var(--cf-text)]">
                    Security &amp; Session Management
                  </h2>
                  <p className="text-xs text-[var(--cf-text-muted)] mt-0.5">
                    How your credentials, sessions, and private tokens are protected
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  
                  {/* Item 1: 2FA */}
                  <div className="p-4 rounded-2xl bg-[var(--cf-surface-alt)] border border-[var(--cf-border-soft)] space-y-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Key className="w-4 h-4 text-[var(--cf-accent)]" />
                        <span className="font-semibold text-xs text-[var(--cf-text)]">
                          Two-Factor Authentication (2FA)
                        </span>
                      </div>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-600 font-bold border border-emerald-500/20">
                        Protected
                      </span>
                    </div>
                    <p className="text-[11px] text-[var(--cf-text-muted)] leading-relaxed">
                      Time-based OTP &amp; WebAuthn biometric passkeys supported via Supabase Auth.
                    </p>
                  </div>

                  {/* Item 2: Encryption */}
                  <div className="p-4 rounded-2xl bg-[var(--cf-surface-alt)] border border-[var(--cf-border-soft)] space-y-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Lock className="w-4 h-4 text-[var(--cf-accent)]" />
                        <span className="font-semibold text-xs text-[var(--cf-text)]">
                          Encryption Standards
                        </span>
                      </div>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[var(--cf-surface)] text-[var(--cf-text)] font-bold border border-[var(--cf-border)]">
                        AES-256
                      </span>
                    </div>
                    <p className="text-[11px] text-[var(--cf-text-muted)] leading-relaxed">
                      All calculations run in your client runtime. No financial data leaves in plaintext.
                    </p>
                  </div>

                </div>

                {/* Active Sessions List */}
                <div className="pt-4 border-t border-[var(--cf-border-soft)]">
                  <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-[var(--cf-text)] mb-3">
                    Active Verified Sessions
                  </h3>
                  <div className="p-4 rounded-2xl border border-[var(--cf-border-soft)] flex items-center justify-between text-xs">
                    <div className="flex items-center gap-3">
                      <Smartphone className="w-4 h-4 text-[var(--cf-accent)]" />
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="font-semibold text-[var(--cf-text)]">Current Browser Session</span>
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                          <span className="text-[10px] font-mono text-emerald-600">Active Now</span>
                        </div>
                        <span className="text-[10px] font-mono text-[var(--cf-text-muted)]">
                          IP address &amp; telemetry masked by zero-surveillance policy
                        </span>
                      </div>
                    </div>

                    <button
                      type="button"
                      onClick={signOut}
                      className="text-xs font-mono text-[var(--cf-caution)] hover:underline cursor-pointer"
                    >
                      Revoke Session
                    </button>
                  </div>
                </div>

              </div>
            </motion.div>
          )}

          {/* TAB 3: SUBSCRIPTION & BILLING */}
          {activeTab === 'billing' && (
            <motion.div
              key="billing"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="space-y-6"
            >
              <div 
                className="p-6 sm:p-8 rounded-3xl border space-y-6"
                style={{ background: 'var(--cf-surface)', borderColor: 'var(--cf-border)' }}
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[var(--cf-border-soft)]">
                  <div>
                    <h2 className="text-base font-serif font-bold text-[var(--cf-text)]">
                      Current Plan &amp; Entitlements
                    </h2>
                    <p className="text-xs text-[var(--cf-text-muted)] mt-0.5">
                      Your active tier and unlocked financial simulation features
                    </p>
                  </div>

                  <Link
                    href="/subscription"
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold text-white shadow-md cursor-pointer"
                    style={{ background: 'linear-gradient(135deg, #2F6F62, #1a4f45)' }}
                  >
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>View All Pricing Plans</span>
                  </Link>
                </div>

                <div className="p-4 sm:p-6 rounded-2xl bg-[var(--cf-surface-alt)] border border-[var(--cf-border-soft)] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-lg font-serif font-bold text-[var(--cf-text)]">
                        {isPro ? 'CashFloor Pro' : 'Starter Ledger'}
                      </span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded-full font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">
                        ACTIVE
                      </span>
                    </div>
                    <p className="text-xs text-[var(--cf-text-muted)] mt-1">
                      {isPro ? '$15/month · Billed annually' : '$0/month · Free forever'}
                    </p>
                  </div>

                  <Link
                    href="/subscription"
                    className="text-xs font-mono font-semibold text-[var(--cf-accent)] hover:underline flex items-center gap-1"
                  >
                    <span>Change Plan</span>
                    <ExternalLink className="w-3 h-3" />
                  </Link>
                </div>

                {/* Feature Checklist */}
                <div className="space-y-3 text-xs">
                  {[
                    '20th-Percentile Survival Runway Calculator',
                    'All 6 Advanced Stress-Test Scenarios (Dry Spell, Client Churn, Windfall, Late Invoices)',
                    'Automated Quarterly Tax Escrow Auto-Partitioner',
                    'Client Revenue Concentration (HHI) & Volatility Radar',
                    'Multi-device Encrypted Cloud Sync & Private Local Vault',
                  ].map(feature => (
                    <div key={feature} className="flex items-center gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                      <span className="text-[var(--cf-text)]">{feature}</span>
                    </div>
                  ))}
                </div>

              </div>
            </motion.div>
          )}

          {/* TAB 4: DATA SOVEREIGNTY & VAULT */}
          {activeTab === 'data' && (
            <motion.div
              key="data"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="space-y-6"
            >
              <div 
                className="p-6 sm:p-8 rounded-3xl border space-y-6"
                style={{ background: 'var(--cf-surface)', borderColor: 'var(--cf-border)' }}
              >
                <div>
                  <h2 className="text-base font-serif font-bold text-[var(--cf-text)]">
                    Data Sovereignty &amp; Vault Controls
                  </h2>
                  <p className="text-xs text-[var(--cf-text-muted)] mt-0.5">
                    Your financial records belong strictly to you. Export or purge anytime.
                  </p>
                </div>

                {exportSuccess && (
                  <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 text-xs font-mono">
                    ✓ Financial ledger exported successfully to your downloads folder.
                  </div>
                )}

                {purgeSuccess && (
                  <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-600 text-xs font-mono">
                    ✓ Local ledger cache cleared from this device.
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  
                  {/* Export */}
                  <div className="p-5 rounded-2xl border border-[var(--cf-border-soft)] bg-[var(--cf-surface-alt)] flex flex-col justify-between">
                    <div>
                      <div className="flex items-center gap-2 mb-2">
                        <Download className="w-4 h-4 text-[var(--cf-accent)]" />
                        <h3 className="text-xs font-semibold text-[var(--cf-text)]">
                          Export All Ledger Records
                        </h3>
                      </div>
                      <p className="text-[11px] text-[var(--cf-text-muted)] leading-relaxed">
                        Download your complete financial history, scenarios, and calculations in machine-readable JSON format for your CPA.
                      </p>
                    </div>

                    <div className="pt-4">
                      <button
                        type="button"
                        onClick={handleExportAllData}
                        className="px-4 py-2 rounded-xl text-xs font-mono font-semibold border transition-all cursor-pointer"
                        style={{
                          borderColor: 'var(--cf-border)',
                          background: 'var(--cf-surface)',
                          color: 'var(--cf-text)',
                        }}
                      >
                        Download Data Package (.json)
                      </button>
                    </div>
                  </div>

                  {/* Purge Local Storage */}
                  <div className="p-5 rounded-2xl border border-red-500/20 bg-red-500/5 flex flex-col justify-between">
                    <div>
                      <div className="flex items-center gap-2 mb-2 text-red-500">
                        <Trash2 className="w-4 h-4" />
                        <h3 className="text-xs font-semibold">
                          Purge Device Storage Cache
                        </h3>
                      </div>
                      <p className="text-[11px] text-[var(--cf-text-muted)] leading-relaxed">
                        Clears all cached income records and assumptions stored in this specific browser. Safe if using a shared computer.
                      </p>
                    </div>

                    <div className="pt-4">
                      <button
                        type="button"
                        onClick={handlePurgeLocalData}
                        className="px-4 py-2 rounded-xl text-xs font-mono font-semibold border border-red-500/30 text-red-600 hover:bg-red-500/10 transition-all cursor-pointer"
                      >
                        Purge Local Cache
                      </button>
                    </div>
                  </div>

                </div>

                {/* Privacy Guarantee Banner */}
                <div className="p-4 rounded-2xl bg-[var(--cf-accent-bg)] border border-[var(--cf-accent)]/20 text-xs text-[var(--cf-text-muted)] flex items-start gap-3">
                  <ShieldCheck className="w-5 h-5 text-[var(--cf-accent)] shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold text-[var(--cf-text)] block mb-0.5">
                      GDPR &amp; Zero Surveillance Guarantee
                    </span>
                    <span>
                      CashFloor does not sell, analyze, or train AI models on your financial data. Every calculation is performed within your local browser sandbox.
                    </span>
                  </div>
                </div>

              </div>
            </motion.div>
          )}

        </AnimatePresence>

      </main>
    </div>
  );
}
