/**
 * Generates an RFC 5545 compliant iCalendar (.ics) string for quarterly estimated tax deadlines
 */

export interface TaxDeadlineEvent {
  title: string;
  description: string;
  startDate: string; // YYYYMMDD
  endDate: string;   // YYYYMMDD
  quarter: string;
}

export function generateTaxDeadlinesIcs(): string {
  const currentYear = new Date().getFullYear();
  const nextYear = currentYear + 1;

  const events: TaxDeadlineEvent[] = [
    {
      quarter: 'Q1',
      title: `IRS Estimated Tax Payment — Q1 (${currentYear})`,
      description: `Q1 Quarterly Estimated Tax Deadline for Freelancers and Independent Contractors. Ensure your tax escrow buffer is remitted to avoid underpayment penalties.\\n\\nPay online: https://www.irs.gov/payments\\nGenerated by CashFloor (https://cashfloor.app)`,
      startDate: `${currentYear}0415T090000`,
      endDate: `${currentYear}0415T100000`,
    },
    {
      quarter: 'Q2',
      title: `IRS Estimated Tax Payment — Q2 (${currentYear})`,
      description: `Q2 Quarterly Estimated Tax Deadline for Freelancers and Independent Contractors. Remit second-quarter estimated income and self-employment taxes.\\n\\nPay online: https://www.irs.gov/payments\\nGenerated by CashFloor (https://cashfloor.app)`,
      startDate: `${currentYear}0615T090000`,
      endDate: `${currentYear}0615T100000`,
    },
    {
      quarter: 'Q3',
      title: `IRS Estimated Tax Payment — Q3 (${currentYear})`,
      description: `Q3 Quarterly Estimated Tax Deadline for Freelancers and Independent Contractors. Third quarter estimated tax due date.\\n\\nPay online: https://www.irs.gov/payments\\nGenerated by CashFloor (https://cashfloor.app)`,
      startDate: `${currentYear}0915T090000`,
      endDate: `${currentYear}0915T100000`,
    },
    {
      quarter: 'Q4',
      title: `IRS Estimated Tax Payment — Q4 (${currentYear} Fiscal Year)`,
      description: `Q4 Final Quarterly Estimated Tax Deadline for Freelancers. Fourth quarter estimated tax due date.\\n\\nPay online: https://www.irs.gov/payments\\nGenerated by CashFloor (https://cashfloor.app)`,
      startDate: `${nextYear}0115T090000`,
      endDate: `${nextYear}0115T100000`,
    },
  ];

  const nowStamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const vEvents = events
    .map((ev, index) => {
      return `BEGIN:VEVENT
UID:cashfloor-tax-${ev.quarter}-${currentYear}-${index}@cashfloor.app
DTSTAMP:${nowStamp}
DTSTART:${ev.startDate}
DTEND:${ev.endDate}
SUMMARY:${ev.title}
DESCRIPTION:${ev.description}
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-P7D
ACTION:DISPLAY
DESCRIPTION:Reminder: ${ev.title} due in 1 week
END:VALARM
BEGIN:VALARM
TRIGGER:-P1D
ACTION:DISPLAY
DESCRIPTION:Urgent: ${ev.title} due tomorrow
END:VALARM
END:VEVENT`;
    })
    .join('\r\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//CashFloor Technologies//Freelance Tax Deadlines//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:CashFloor Quarterly Tax Deadlines',
    'X-WR-TIMEZONE:UTC',
    vEvents,
    'END:VCALENDAR',
  ].join('\r\n');
}

export function downloadTaxCalendarFile(): void {
  const icsData = generateTaxDeadlinesIcs();
  const blob = new Blob([icsData], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `cashfloor-quarterly-tax-deadlines-${new Date().getFullYear()}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
